# Generated by Django 4.1.5 on 2025-02-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='apikey_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='business_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='external_lookup_id',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
    ]
